version: '3.8'

services:
  # nginx:
  #   build: ./nginx
  #   ports:
  #     - 1337:80
  #   depends_on:
  #     - web
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    command: gunicorn --bind 0.0.0.0:5000 --chdir /home/app/web/ wsgi:app
    # command: tail -F anything
    volumes:
      - ./src/:/usr/src/app/
    expose:
      - 5000
    env_file:
      - ./.env.prod