name: publish

on:
  push:
    branches: [ "main" ]

jobs:
  publish-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build the project Docker image
      run: |
        echo $CR_PAT | docker login ghcr.io -u rsouza01 --password-stdin
      env:
        CR_PAT: ${{ secrets.SA_PAT }}