name: Publish

on:
  push:
    branches: [ "main" ]

jobs:
  publish-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the Docker image
      run: |
        make prod-build
        # docker build . --tag ghcr.io/rsouza01/runtime-executor:latest
        # docker run ghcr.io/rsouza01/runtime-executor:latest
        # docker push ghcr.io/rsouza01/runtime-executor:latest
